model:
  name: 'efficientnet'
  saved_model: '' # Path to saved model

trainer:
  task: 'classification'
  lr: 0.001
  optimizer: 'adam'
  loss: 'cross_entropy'
  epochs: 10
  betas: [0.9, 0.999]

dataset:
  validation_split: 0.3
  classes: [0, 1] # Last is minority
  batch_size: 100
  oversampling: 'gan' # none, oversampling or gan
  gan_model:
    name: 'wgan' 
    saved_model: 'output/saved_models/WGAN' # path to saved model if oversampling is gan