task: 'generation'

model:
  name: 'wgan'
  saved_model: '' # Path to saved model
  args:
    generator_iters: 10000

optimizer:
  lr: 0.001

dataset:
  validation_split: 0
  classes: [1]
  batch_size: 100
  oversampling: 'none'
  saved_model: ''