model:
  name: 'wgan'
  saved_model: 'output/saved_models/WGAN' # Path to saved model

trainer:
  task: 'generation'
  lr: 0.0001
  optimizer: 'adam'
  epochs: 5000 # here, epochs refers to the number of generator iterations
  betas: [0.5, 0.999]

dataset:
  validation_split: 0
  classes: [1]
<<<<<<< HEAD
  batch_size: 32
=======
  batch_size: 64
>>>>>>> 1d6922fb87c162eb5d20967475fcee69a7cb7760
  oversampling: 'none'
  gan_model:
    name: '' 
    saved_model: ''
